package portalbr.dbobj.table;

/** DataBase Object from table WBRIO.Controle_clientes_especiais_vw
  * @version 09/09/2022 13:23:54
  */
public class Controle_clientes_especiais_vwMetaData {

  public static final String SCHEMA = "WBRIO";

  /*** Table Primary Key fields. */
  public static final String[] PK = new String[0];

  /*** Data Base object name. */
  public static final String DB_OBJECT = "CONTROLE_CLIENTES_ESPECIAIS_VW";

  /*** Method for getting table metadada. 
     * { type, name, length, not_null (parameter type), html_type, label, format, validate_type, case_restriction } */
  public static String[][] getMetadata() {
    String[][] metadata = {
                            {"java.lang.Integer","ped_nmro","22","true","text","Ped_nmro","","","true","","","",},
                            {"java.lang.Double","ped_boni","7","true","text","Ped_boni","","##,##0.00","true","","","",},
                            {"java.lang.Double","ped_boni2","7","true","text","Ped_boni2","","##,##0.00","true","","","",},
                            {"java.lang.Double","ped_desc","7","true","text","Ped_desc","","##,##0.00","true","","","",},
                            {"java.lang.String","cnd_cdgo","100","true","text","Cnd_cdgo","","","true","","","",},
                            {"java.lang.String","oc","100","false","text","Oc","","","","","","",},
                            {"java.lang.String","modelos","4000","false","text","Modelos","","","","","","",},
                            {"java.lang.String","etiquetas","200","false","text","Etiquetas","","","","","","",},
                            {"java.lang.String","obse_adicionais","400","false","text","Obse_adicionais","","","","","","",},
                            {"java.lang.Integer","prs","22","false","text","Prs","","","true","","","",},
                            {"java.lang.String","remessa","200","false","text","Remessa","","","true","","","",},
                            {"java.lang.String","filial_prd","4","false","text","Filial_prd","","","","","","",},
                            {"java.lang.String","fil_filial_fat","4","false","text","Fil_filial_fat","","","","","","",},
                            {"java.sql.Date","dt_emiss","19","false","text","Dt_emiss","","dd/MM/yyyy","true","","","",},
                            {"java.sql.Date","dt_digit","19","false","text","Dt_digit","","dd/MM/yyyy","true","","","",},
                            {"java.sql.Date","dt_fatur","19","true","text","Dt_fatur","","dd/MM/yyyy","true","","","",},
                            {"java.sql.Date","dt_fatur_filial","19","false","text","Dt_fatur_filial","","dd/MM/yyyy","true","","","",},
                            {"java.lang.String","marca","200","false","text","Marca","","","","","","",},
                            {"java.lang.String","carimbo","200","false","text","Carimbo","","","","","","",},
                            {"java.lang.String","rotulos","200","false","text","Rotulos","","","","","","",},
                            {"java.lang.String","ped_amostra","200","false","text","Ped_amostra","","","true","","","",},
                            {"java.sql.Date","dt_envio_amostras","19","false","text","Dt_envio_amostras","","dd/MM/yyyy","true","","","",},
                            {"java.lang.String","agendamento_cdgo","20","false","text","Agendamento_cdgo","","","true","","","",},
                            {"java.sql.Date","data_efetiva","22","false","text","Data_efetiva","","dd/MM/yyyy","true","","","",},
                            {"java.lang.Integer","codigo_regional","3","false","text","Codigo_regional","","","true","","","",},
                            {"java.lang.String","nome_regional","50","true","text","Nome_regional","","","","","","",},
                            {"java.lang.String","rep_cdgo","5","true","text","Rep_cdgo","","","","","","",},
                            {"java.lang.Integer","cli_cdgo","22","true","text","Cli_cdgo","","","true","","","",},
                            {"java.lang.Integer","esc_seqn","10","true","text","Esc_seqn","","","true","","","",},
                            {"java.lang.Integer","codigo_marca","-127","false","text","Codigo_marca","","","true","","","",},
                            {"java.lang.String","ped_stat","10","false","text","Ped_stat","","","true","","","",},
                            {"java.lang.String","existe","1","false","text","Existe","","","true","","","",},
                            {"java.lang.String","hora","20","false","text","Hora","","","true","","","",},
                            {"java.lang.String","senha","20","false","text","Senha","","","true","","","",},
                            {"java.sql.Timestamp","dt_emissao","19","false","text","Dt_emissao","","","true","","","",},
                            {"java.lang.String","filial","20","false","text","Filial","","","true","","","",},
                            {"java.lang.String","notafiscal","20","false","text","NF","","","true","","","",},
                            {"java.lang.String","volumes","20","false","text","Volumes","","","true","","","",},
                            {"java.lang.String","rep_rzao","50","false","text","Rep_rzao","","","true","","","",},
                            {"java.lang.String","esc_seqn","10","false","text","Esc_seqn","","","true","","","",},
                            {"double","valor_pedido","22","false","text","double","","","true","","","",},
                            {"java.lang.String","cli_rzao","50","false","text","Cli_rzao","","","true","","","",},
                            {"java.lang.String","grupo_economico","50","false","text","Grupo_economico","","","true","","","",},
                            {"java.lang.String","grupo_descricao","100","false","text","Grupo_descricao","","","true","","","",},
                            {"java.sql.Date","dt_inspecao","19","false","text","Dt_inspecao","","dd/MM/yyyy","true","","","",},
                            {"java.sql.Date","dt_entrega_etiqueta","19","false","text","Dt_entrega_etiqueta","","dd/MM/yyyy","true","","","",},
                            {"java.sql.Date","dt_montagem","19","false","text","Dt_montagem","","dd/MM/yyyy","true","","","",},
                            {"java.lang.String","dados_cadastrados","1","false","text","Dados_cadastrados","","","true","","","",},
                            {"java.lang.String","possui_carimbo","1","false","text","Possui_carimbo","","","true","","","",},
                            {"java.lang.String","somente_etiqueta","1","false","text","Somente_etiqueta","","","true","","","",},
                            {"java.lang.String","situacao","20","false","text","Situação","","","","","","",},
                            {"java.lang.String","cabide","200","false","text","Cabide","","","","","","",},
                            {"java.lang.String","amostra","1","false","text","Amostra","","","","","","",},
                            {"java.lang.String","tipo_amostra","100","false","text","Tipo_amostra","","","","","","",},
                            {"java.lang.String","pedido_prod","4000","false","text","Pedido_prod","","","","","","",},
                            {"java.sql.Date","dt_ent_amostra_comercial","19","false","text","Dt_ent_amostra_comercial","","dd/MM/yyyy","true","","","",},
                            {"java.sql.Date","dt_ent_amostra_pcp","19","false","text","Dt_ent_amostra_pcp","","dd/MM/yyyy","true","","","",},
                            {"java.lang.String","encarte","4000","false","text","Encarte","","","","","","",},
                            {"java.lang.String","ped_amostra_brinde","100","false","text","ped_amostra_brinde","","","true","","","",},
                            {"java.lang.String","ped_obse","130","false","text","Observação Pedido","","","","","","",},
                            {"java.lang.String","portao","60","false","text","Portão de Entrega","","","","","","",},
                            {"java.lang.String","cd_entrega","60","false","text","CD de Entrega","","","","","","",},
                            {"java.lang.String","ped_amostra_brinde","200","false","text","Amostra Brinde","","","","","","",},
                            {"java.sql.Date","data_entrega_cliente","19","false","text","Dt_digit","","dd/MM/yyyy","true","","","",},
                            {"java.lang.String","ped_tipo","10","false","text","Ped_tipo","","","","","","",},
                            {"java.sql.Date","dt_rec_etiqueta_filial","19","false","text","Dt_rec_etiqueta_filial","","dd/MM/yyyy","true","","","",},
                            {"java.lang.String","prioridade_embarque","1","false","text","Prioridade_embarque","","","","","","",},
                            {"java.lang.String","atacado","1","false","text","Atacado","","","","","","",},
                            {"java.lang.String","alerta","1","false","text","Alerta","","","","","","",},
                            {"java.lang.String","ped_especie_pedido","1","false","text","Ped_especie_pedido","","","","","","",},
                            {"java.lang.String","ped_obse","200","false","text","Ped_obse","","","","","","",},
                            {"java.lang.Integer","nro_normativa_cliente","10","false","text","Nro_normativa_cliente","","","","","","",},
                            {"java.lang.String","descricao_normativa_cliente","300","false","text","Descricao_normativa_cliente","","","","","","",},
                            {"java.lang.String","min_fabr","300","false","text","Min_fabr","","","","","","",},
                            {"java.lang.String","bloqueio_49","30","false","text","Bloqueio_49","","","","","","",},
                            {"java.lang.String","loja","60","false","text","Loja","","","","","","",},
                            {"java.lang.String","cidade","100","false","text","Cidade","","","","","","",},
                            {"java.lang.String","ped_invoice","100","false","text","Ped_invoice","","","","","","",},
                            {"java.lang.String","ocorrencia","100","false","text","ocorrencia","","","","","","",},
                            {"java.sql.Date","data_bloqueio","19","false","text","data_bloqueio","","dd/MM/yyyy","true","","","",},
                            {"java.sql.Date","data_prevista_desbloqueio","19","false","text","data_prevista_desbloqueio","","dd/MM/yyyy","true","","","",},
                            {"java.sql.Date","dt_solicitacao_alarme","19","false","text","dt_solicitacao_alarme","","dd/MM/yyyy","true","","","",},
                            {"java.sql.Date","dt_rec_alarme_pcp","19","false","text","dt_rec_alarme_pcp","","dd/MM/yyyy","true","","","",},
                            {"java.sql.Date","dt_rec_alarme_filial","19","false","text","dt_rec_alarme_filial","","dd/MM/yyyy","true","","","",},
                            {"java.lang.Integer","nfe_numero","22","true","text","Nfe_numero","","","true","","","",},
                            {"java.lang.Integer","existe_log_ped_inf_add","22","true","text","existe_log_ped_inf_add","","","true","","","",},
                            {"java.lang.String","distribuicao","100","false","text","Distribuição","","","","","","",},
                            {"java.lang.String","livro","100","false","text","Livro","","","","","","",},
                            {"java.lang.String","ref_cliente_por_pedido","10","false","text","Ref_cliente_por_pedido","","","","","","",},
                            {"java.lang.Integer","tra_cdgo","22","true","text","Tra_cdgo","","","true","","","",},
                            {"java.lang.String","tra_rzao","100","false","text","Tra_rzao","","","","","","",},
                            {"java.sql.Date","dt_corte","19","false","text","Dt_corte","","dd/MM/yyyy","true","","","",},
                            {"java.lang.String","bloqueado_credito","30","false","text","Bloqueado_credito","","","","","","",},
                            {"java.lang.String","preco_pdv","22","false","text","Preco_pdv","","","","","","",},
                            {"java.lang.String","certificado_origem","400","false","text","Certificado_origem","","","","","","",},
                            {"java.lang.String","gerar_requisicao","10","false","text","Gerar_requisicao","","","","","","",},
                            {"java.lang.Integer","les_codigo","22","true","text","les_codigo","","","true","","","",},
                            {"java.lang.String","tes_codigo","100","true","text","tes_codigo","","","true","","","",},
                            {"java.sql.Date","data_etiquetagem","19","false","text","Data_etiquetagem","","dd/MM/yyyy","true","","","",},
                            {"java.lang.String","descricao_modelos","4000","false","text","Descrição","","","","","","",},
                            {"java.lang.String","liberado_faturar","10","false","text","liberado_faturar","","","","","","",},
                            {"java.lang.String","descricao_situacao","240","false","text","descricao_situacao","","","","","","",},
                            {"java.lang.String","descricao_embalagem","240","false","text","descricao_embalagem","","","","","","",},
                            {"java.lang.String","cnpj","100","true","text","Cnpj","","","true","","","",},
                            {"java.lang.String","numero_romaneio","50","true","text","Numero_romaneio","","","true","","","",},
                            {"java.lang.String","data_finalizacao_romaneio","50","true","text","Data_finalizacao_romaneio","","","true","","","",},
                            {"java.lang.String","modelo_alarme","200","true","text","Modelo_alarme","","","true","","","",},
                            {"java.lang.String","grades_corrugados","4000","true","text","Grades_corrugados","","","true","","","",},
                            {"java.lang.String","filial_local_estoque","20","true","text","Filial_local_estoque","","","true","","","",},
                            {"java.lang.String","bloqueio_oc","20","true","text","bloqueio_oc","","","true","","","",},
                            {"java.lang.String","bloqueio_distribuicao","20","true","text","bloqueio_distribuicao","","","true","","","",},
                            {"java.lang.String","bloqueio_cliente","20","true","text","bloqueio_cliente","","","true","","","",},
                            {"java.lang.String","bloqueio_sku","20","true","text","bloqueio_sku","","","true","","","",},
                            {"java.lang.String","bloqueio_credito","20","true","text","bloqueio_credito","","","true","","","",},
                            {"java.lang.String","bloqueio_suframa","20","true","text","bloqueio_suframa","","","true","","","",}
                          };
    return metadata;
  }

}
